version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean
      - mvn install
artifacts:
  files:
    - 'Dockerfile'
    - target/nlp-application-1.0-SNAPSHOT.jar
